theme = "flexoki-dark"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "underline"
normal = "underline"
select = "underline"

[editor.indent-guides]
render = true
