theme = "flexoki_dark"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-s = ":w"
X = "extend_line_above"

[keys.select]
X = "extend_line_above"

# Git
[keys.normal.space.g]
g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":set mouse false", # First disable mouse to hint helix into activating it
    ":set mouse true",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
f = "changed_file_picker"
r = ":reset-diff-change"
# inline blame
b = ":run-shell-command ~/.config/helix/utils/blame_line_pretty.sh %{buffer_name} %{cursor_line}"
# full file changes of last commit under cursor
B = ':open %sh{~/.config/helix/utils/blame_file_pretty.sh %{buffer_name} %{cursor_line}}'
# inline hunk changes
h = ':run-shell-command ~/.config/helix/utils/git-hunk.sh %{buffer_name} %{cursor_line} 3'
